"""Add transcription fields

Revision ID: b9e99503d04b
Revises: e417285ddd49
Create Date: 2026-09-06 01:17:28.988304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b9e99503d04b'
down_revision: Union[str, Sequence[str], None] = 'e417285ddd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('detected_language', sa.String(length=10), nullable=True))
    op.add_column('reports', sa.Column('transcription_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'transcription_confidence')
    op.drop_column('reports', 'detected_language')
    # ### end Alembic commands ###
