"""Add Gemini AI Priority fields

Revision ID: da17decd1539
Revises: b9e99503d04b
Create Date: 2026-09-06 02:45:38.135724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'da17decd1539'
down_revision: Union[str, Sequence[str], None] = 'b9e99503d04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analyses', sa.Column('detected_priority', sa.String(length=50), nullable=True))
    op.add_column('ai_analyses', sa.Column('immediate_danger', sa.Boolean(), nullable=True))
    op.add_column('ai_analyses', sa.Column('recommended_action', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_analyses', 'recommended_action')
    op.drop_column('ai_analyses', 'immediate_danger')
    op.drop_column('ai_analyses', 'detected_priority')
    # ### end Alembic commands ###
